language: go
go: 
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - tip

matrix:
  allow_failures:
    - go: tip

install:
 - rm -rf $GOPATH/src/gopkg.in/davaops
 - mkdir -p $GOPATH/src/gopkg.in/davaops
 - ln -s $PWD $GOPATH/src/gopkg.in/davaops/go-syslog.v3
 - cd $GOPATH/src/gopkg.in/davaops/go-syslog.v3 && go get -v -t ./...
 
script:
 - cd $GOPATH/src/gopkg.in/davaops/go-syslog.v3 && go test -v ./...
 
sudo: false
